import React from "react";

const New = () => {
  return (
    <div>
      <div>
        <p>
          <img
            decoding="async"
            classname="swiper-slide-image"
            src="https://d3r3au5ai04saj.cloudfront.net/wp-content/uploads/2023/01/cellcome-1-150x150.png"
            alt="cellcome"
          />
        </p>
        <p>
          <img
            decoding="async"
            classname="swiper-slide-image"
            src="https://d3r3au5ai04saj.cloudfront.net/wp-content/uploads/2022/11/1-150x150.png"
            alt="{1}"
          />
        </p>
        <p>
          <img
            decoding="async"
            classname="swiper-slide-image"
            src="https://d3r3au5ai04saj.cloudfront.net/wp-content/uploads/2022/11/3-150x150.png"
            alt="{3}"
          />
        </p>
        <p>
          <img
            decoding="async"
            classname="swiper-slide-image"
            src="https://d3r3au5ai04saj.cloudfront.net/wp-content/uploads/2022/11/4-150x150.png"
            alt="{4}"
          />
        </p>
        <p>
          <img
            decoding="async"
            classname="swiper-slide-image"
            src="https://d3r3au5ai04saj.cloudfront.net/wp-content/uploads/2022/11/5-150x150.png"
            alt="{5}"
          />
        </p>
        <p>
          <img
            decoding="async"
            classname="swiper-slide-image"
            src="https://d3r3au5ai04saj.cloudfront.net/wp-content/uploads/2022/11/2-150x150.png"
            alt="{2}"
          />
        </p>
        <p>
          <img
            decoding="async"
            classname="swiper-slide-image"
            src="https://d3r3au5ai04saj.cloudfront.net/wp-content/uploads/2022/11/6-150x150.png"
            alt="{6}"
          />
        </p>
        <p>
          <img
            decoding="async"
            classname="swiper-slide-image"
            src="https://d3r3au5ai04saj.cloudfront.net/wp-content/uploads/2022/11/logos-zahal-150x150.png"
            alt="logos-zahal"
          />
        </p>
        <p>
          <img
            decoding="async"
            classname="swiper-slide-image"
            src="https://d3r3au5ai04saj.cloudfront.net/wp-content/uploads/2023/03/AFI-150x150.png"
            alt="AFI"
          />
        </p>
        <p>
          <img
            decoding="async"
            classname="swiper-slide-image"
            src="https://d3r3au5ai04saj.cloudfront.net/wp-content/uploads/2023/04/TerminalX-150x150.png"
            alt="TerminalX"
          />
        </p>
        <p>
          <img
            decoding="async"
            classname="swiper-slide-image"
            src="https://d3r3au5ai04saj.cloudfront.net/wp-content/uploads/2023/04/Matah-150x150.png"
            alt="Matah"
          />
        </p>
        <p>
          <img
            decoding="async"
            classname="swiper-slide-image"
            src="https://d3r3au5ai04saj.cloudfront.net/wp-content/uploads/2023/05/Club-Med-Logo-150x150.png"
            alt="Club Med Logo"
          />
        </p>
      </div>
    </div>
  );
};

export default New;
